### PR TITLE
refactor: delete decafAPI - removed from pathwaypredictor

### PR DESCRIPTION
**Pull request by matyasfodor**

### CODE REVIEW

**Review by kvikshaug — APPROVED** [review]
Your message says "delete decafAPI" but I guess you mean "delete pathwaysAPI" :)

I like the idea of moving towards a single decafAPIProvider for all services. However, is there a use case to configure a local dev environment to use a mixture of API environments? E.g. use the staging model service, but develop against a local pathways instance. If so, maybe separate providers are necessary?

**Comment by kvikshaug** [comment]
Oh, can you please also remove `PATHWAYS_API` from:

* webpack config
* circle-environment.sh
* The env configuration on circleci.com

**Comment by matyasfodor** [comment]
@kvikshaug You're right. So what's your take on this? I think in the pathway predictor should fetch the available models from the same endpoint as the pathway visualizer. But you're right, for the prediction it could use a different endpoint.

I should also note that now we have a staging and production environment for all backend services. I guess it makes sense to fetch the same API.

Here's my proposal:
 - Now: 
   - Restore the pathwaysAPI in the pathway predictor
   - Have the decafAPI next to pathwaysAPI in pathway predictor
 - Later:
   - Each backend service is under it's own sub-url `/pathway-predictor` or `/ninja`, `model-service`. I guess it's easy to do in NGINX, no change in code is required in the services.
   - Each service is represented with a meaningful provider in the angular apps. eg. `modelAPI` instead of `decafAPI`.

This would be relatively low effort but would make our infrastructure much easier to understand.

**Comment by kvikshaug** [comment]
I think you've sketched out the ideal scenario here both short and long term and I support this proposal.

> I guess it's easy to do in NGINX, no change in code is required in the services.

I have a side note about this. If you add a trailing slash to the [`proxy_pass`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass) URI, it will get rewritten.

    location /models {
        proxy_pass http://model:8000/;
    }

Here a request to `https://api.dd-decaf.eu/models/model/iJO1366` would proxy to `http://model:8000/model/iJO1366`, as we want.

However, in some cases, the application needs to know the full URI. In the IAM service, I used this scheme with success, until I added [Flask-Admin](https://flask-admin.readthedocs.io/en/latest/). Since it renders html, it needs to know to prepend `/iam` to `src` and `href` attributes. [Check it out at https://api-staging.dd-decaf.eu/iam/admin/](https://api-staging.dd-decaf.eu/iam/admin/)

So for IAM we need to know the [`SERVICE_URL` prefix](https://github.com/dd-decaf/iam#environment). There could be similar conditions in the other services, say f.ex. if we want to link/reference other resources for related objects. But I guess ideally we would design our services to be agnostic about it.

**Pull request closed without merging**
